function sats = createConstellation(sc, CFG)
% Idealized Walker Delta 53:1584/72/39, not operational Starlink ephemerides.
% Neighbor-plane anomaly offset = 360*F/T; within-plane spacing = 360/S.
validateattributes(CFG.numPlanes,{'numeric'},{'scalar','integer','positive'});
validateattributes(CFG.satsPerPlane,{'numeric'},{'scalar','integer','positive'});
validateattributes(CFG.phaseFactor,{'numeric'}, ...
    {'scalar','integer','>=',0,'<',CFG.numPlanes});
validateattributes(CFG.satAltitude_m,{'numeric'},{'scalar','positive','finite'});
sats = walkerDelta(sc, CFG.earthEquatorialRadius_m + CFG.satAltitude_m, ...
    CFG.inclination_deg, CFG.numPlanes*CFG.satsPerPlane, ...
    CFG.numPlanes, CFG.phaseFactor, ...
    'RAAN',CFG.raan0_deg,'ArgumentOfLatitude',CFG.argumentOfLatitude0_deg, ...
    'OrbitPropagator','two-body-keplerian','Name','StarlinkLike');
end
