function reportPacketResults(L,P,M,CFG)
% Concise reporting; packet and physical calculations are unchanged.
P.rolling_loss_ratio_pct=M.rollingPacketLossRatio;
P.cumulative_generated=M.cumulativeGenerated;
P.cumulative_transmitted=M.cumulativeTransmitted;
P.cumulative_received=M.cumulativeReceived;
P.cumulative_lost=M.cumulativeLost;
summary=sprintf(['===== GSL Simulation Summary =====\n' ...
    'Simulation Time       : %g s\n\nGround Station\n' ...
    'Latitude              : %.4f deg\nLongitude             : %.4f deg\nAltitude              : %g m (WGS84)\n' ...
    '\nLEO Constellation\nAltitude              : %g km\nInclination           : %g deg\nMin Elevation         : %g deg\n' ...
    '\nUDP Traffic (simulated)\nPacket Size           : %g Bytes\nPacket Rate           : %g packets/s\n' ...
    '\nPackets\nGenerated             : %d\nTransmitted           : %d\nReceived              : %s\nLost                  : %s\n' ...
    'Packet Loss Ratio     : %s\n\nHandover\nTotal Handovers       : %d\n' ...
    '==================================\n'], ...
    CFG.duration_s,CFG.gsLatitude_deg,CFG.gsLongitude_deg,CFG.gsAltitude_m, ...
    CFG.satAltitude_m/1e3,CFG.inclination_deg,CFG.minElevation_deg, ...
    CFG.packetSize_bytes,CFG.packetRate_pps,M.generatedPackets,M.transmittedPackets, ...
    number(M.receivedPackets),number(M.lostPackets),percentage(M.packetLossRatio),sum(L.handoverEvent));
fprintf('%s',summary);
if M.pendingPackets>0
    fprintf('Packet loss unavailable: validated PER model required\n');
end
if CFG.exportResults
    if ~isfolder(CFG.outputDir), mkdir(CFG.outputDir); end
    writetable(P,fullfile(CFG.outputDir,'packet_results.csv'));
    writetable(L,fullfile(CFG.outputDir,'link_state.csv'));
    save(fullfile(CFG.outputDir,'packet_results.mat'),'P','M','L','CFG','-v7');
    fid=fopen(fullfile(CFG.outputDir,'packet_summary.txt'),'w','n','UTF-8');
    assert(fid>=0,'Cannot open summary output.');
    cleanup=onCleanup(@() fclose(fid)); %#ok<NASGU>
    fprintf(fid,'%s',summary);
    if M.pendingPackets>0
        fprintf(fid,'Packet loss unavailable: validated PER model required\n');
    end
    % Retire only known obsolete files generated by earlier versions here.
    obsolete={'visibility.png','environment_3d.png','link_state.png'};
    if ~any(isfinite(M.rollingPacketLossRatio))
        obsolete{end+1}='rolling_packet_loss.png';
    end
    for i=1:numel(obsolete)
        path=fullfile(CFG.outputDir,obsolete{i});
        if isfile(path), delete(path); end
    end
end
if CFG.makePlots, plotResults(L,P,M,CFG); end
end
function s=number(v)
if isnan(v), s='N/A'; else, s=sprintf('%g',v); end
end
function s=percentage(v)
if isnan(v), s='N/A'; else, s=sprintf('%.2f %%',v); end
end
